### ISSUE TITLE
KeyEvents Block Not getting extracted

### ISSUE THREAD

**Issue by hnmandlik** [sid5432/jsOTDR#1]
Hi
the key events block is not getting extracted.
Can you help me with this please

**Comment by sid5432** [comment]
Hi,

I had a look at the file. I don't think there is a key events block in the file, at least not as defined by the standards. Following the FxdParams block, there is a proprietary blocks: NetTestTSI, followed by the standard DataPts block, but then there are more proprietary blocks: ARSpecial, AREvent, and WaveMTSParams. Perhaps the AREvent block is what you are looking for (starting at 0xCC60, 196 bytes)? I'm afraid you'll have to dig into that yourself (with a binary file editor) to see what is going on in that section.

**Comment by hnmandlik** [comment]
Thanks for your email!

Could you please suggest a binary file editor that can be used?
I am completely new to this.

**Comment by sid5432** [comment]
If you are using Linux, you can try [bless](https://github.com/bwrsandman/Bless). If you are using Ubuntu, then a simple "sudo apt-get install bless" will install this for you. 

If you are using Windows, then I'm afraid I don't have any suggestions, because I've never needed to use a binary/hex editor in Windows before. 

Hope this helps.

**Comment by hnmandlik** [comment]
Thanks a lot for your reply

**Comment by hnmandlik** [comment]
We have done some work on extraction of the blocks.

We need some help in understanding the  encoding/encryption used to save
the data inside the blocks (E.g. AREvents, ARSpecials).

Could you please connect me to someone who can help me with this for a fee?

Thanks and regards,
Hemant

**Comment by sid5432** [comment]
I don't know of anybody who is available for such work, and I don't have time for this right now. I have not seen the contents of the blocks to know what is involved, but trying to figure out the encoding of these things can be an open-ended problem that may take a long time to solve. Hopefully the company who wrote this isn't encrypting it! But even without encryption, you will need plenty of examples (binary content plus known interpretation of the code) to have any hope of figuring out what is in it (if you have their software and equipment, you can generate your own examples of course). If you are lucky, they will use a similar encoding scheme as the standard OTDR SOR file format (same endian and word sizes); but you never know.

Unfortunately, since this is a proprietary encoding, and not universally used (unlike the OTDR SOR standard), there's less of an incentive for people to figure this out in their spare time.

If this is for a commercial application, you might be better off contacting the company and see if you can get some document. You'll probably need to pay a licensing fee, or at least signing an non-disclosure agreement, but it might be worth the money, and will save you time.
